name = "SparseCCSA"
uuid = "d89c45e2-5082-4989-aa21-3a0137f6b149"
authors = ["Gaurav Arya <gauravarya272@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
